# Generated by Django 3.2.10 on 2021-12-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='email address', max_length=100)),
                ('full_name', models.CharField(help_text='firstname and lastname', max_length=100)),
            ],
        ),
    ]
