# Generated by Django 3.2.10 on 2021-12-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscribers', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
